---
# Doc in meta/argument_specs.yaml
ttl: 60
domains:
# domain_name: "{{ domains }}.cloud"
bind_config_name: bind

pdns_path: /etc/powerdns
local_address: 0.0.0.0
user_id: pdns
group_id: pdns
access: '0640'
is_primary: yes
is_secondary: none
...
