---
- Name: Enable "{{ service_name }}"
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    enable: true
    masked: no
- Name: Start "{{ service_name }}" service
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    state: started
    enable: false
- Name: Start and enable "{{ service_name }}" service
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    state: started
    enable: true
- Name: Reload "{{ service_name }}" service
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    state: reload
- Name: Restart "{{ service_name }}" service
  ansible.builtin.systemd_service:
    name: "{{ service_name }}"
    state: restart
...
