---
email_address: admin.{{ current_domain }}
organization_name: none
organization_unit_name: none
base_url: none
current_domain: "{{ domains }}.cloud"
domains:                        # Same variable as pdns role
  - domain1
  - domain2
pki_web_root: "/var/www/pki"
...
