---
- name: Generating private key
  community.crypto.openssl_privatekey:
    path: "{{ pki_path }}/ca/root-ca/private/root-ca.key"
    size: 4096  # More longer because it's during 10 years
    type: RSA
    cipher: auto
    passphrase: "I don't know if i change you"  # TODO Create an issue
    mode: '0600'

- name: Generating CSR
  community.crypto.openssl_csr:
    path: "{{ pki_path }}/ca/root-ca.csr"
    privatekey_path: "{{ pki_path }}/ca/root-ca/private/root-ca.key"
    privatekey_passphrase: "I dont know if i change you"  # TODO Create also an issue 

    common_name: "{{ organization_name }}"
    country_name: "{{ contry_name }}"
    organization_name: "{{ organization_name }}"
    organization_unit_name: "{{ organization_unit_name }}"

    basic_constraints: "CA:TRUE"
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
      - cRLSign
    key_usage_critical: true
    create_subject_key_identifier: true

- name: Generate self-signed
  community.crypto.x509_certificate:
    path: "{{ pki_path }}/ca/root-ca.crt"
    privatekey_path: "{{ pki_path }}/ca/root-ca/private/root-ca.key"
    privatekey_passphrase: "I dont know if i change you"  # TODO Create also an issue 
    csr_path: "{{ pki_path }}/ca/root-ca.csr"
    provider: selfsigned
    selfsigned_not_after: "+3650d"  # 10 years

    selfsigned_create_subject_key_identifier: create_if_not_provided

    key_usage:
      - keyCertSign
      - cRLSign
    basic_constraints:
      - "CA:TRUE"

- name: Generate initial CRL
  community.crypto.x509_crl:
    path: "{{ pki_path }}/ca/crl/root-ca.crl"
    privatekey_path: "{{ pki_path }}/ca/root-ca/private/root-ca.key"

    privatekey_passphrase: "I dont know if i change you"  # TODO Create also an issue 

    digest: sha256

    issuer:
      CN: "{{ organization_name }}"
      O: "{{ organization_name }}"
      OU: "{{ organization_unit_name }}"
      C: "{{ country_name }}"
...
