---
- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.lineinfile:
    path: "{{ apt_mirror_config_path }}/acng.conf"
    line: "ExTreshold: {{ days }}"
    create: yes
    mode: '0644'
  when: "{{ ansible }}"
...
