---
- name: "Create the ns1 registration"
  community.general.powerdns_record:
    name: "ns1.{{ domain_root }}."
    zone: "{{ domain_root }}."
    type: A
    content: "{{ pdns_host }}"
    pdns_host: "{{ pdns_host }}"
    pdns_port: "{{ pdns_port }}"
    pdns_api_key: "{{ pdns_api_key }}"
    state: present
...
