---
# Role execution
role: New_PKI

# Folders
pki_path: /root/pki
pki_dirs:
  - path: "{{ pki_path}}/ca"
  - path: "{{ pki_path }}/certs"
  - path: "{{ pki_path }}/crl"

  - path: "{{ pki_path}}/ca/root-ca"
  - path: "{{ pki_path}}/ca/tls-ca"

# root-ca
  - path: "{{ pki_path }}/ca/root-ca/private"
    mode: '0700'
  - path: "{{ pki_path }}/ca/root-ca/db"
  - path: "{{ pki_path }}/ca/root-ca/crl"

# tls-ca
  - path: "{{ pki_path }}/ca/tls-ca/private"
    mode: '0700'
  - path: "{{ pki_path }}/ca/tls-ca/db"
  - path: "{{ pki_path }}/ca/tls-ca/crl"
 
# Organization infos
email_address: "admin.{{ current_domain }}"
organization_name: none
country_name: none

# Domains
current_domain: "{{ domains }}.cloud"
pki_web_root: "/var/www/pki"

# Key infos
key_size: 4096
key_type: RSA
key_mode: 0600
key_usage:
  - keyCertSign
  - cRLSign
...
