- name: Booting to Network Operating System image
  hosts: serv3
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: "Booting to Network Operating System image"
      dellemc.openmanage.idrac_os_deployment:
        idrac_ip: "192.168.1.32"
        idrac_user: "{{ idrac_user }}"
      idrac_password: "{{ idrac_password }}"
        # share_name: "/Users/hadrienklotz/INFOR/INFRA/ANSIBLE/OSDEPLOYEMENT/playbook.yaml"
        iso_image: "/Users/hadrienklotz/INFOR/INFRA/ANSIBLE/OSDEPLOYEMENT/debian-13.1.0-amd64-netinst.iso"
        expose_duration: 180
        share_password: "{{ idrac_password }}"
      delegate_to: localhost
      tags:
        - network_iso
