---
- name: Generate private key
  community.crypto.openssl_privatekey:
    path: "{{ pki_path }}/ca/{{ item }}.key"
    size: "{{ key_size | default(2048) }}"
    type: "{{ key_type | default('RSA') }}"
    cipher: auto
    passphrase: "passphrase"
    mode: "{{ key_mode }}"
  loop: "{{ domains }}"
  run_once: true

# Grab the openssl community package and put them here
- name: Generate CSR
  community.crypto.openssl_csr:
    path: "{{ pki_path }}/ca/{{ item }}.csr"
    privatekey_path: "{{ pki_path }}/ca/{{ item }}.key"
    privatekey_passphrase: "passphrase"
    common_name: "{{ item }}"
    subject_lat_name: "DNS:{{ item }}"
    country_name: "{{ country_name | default('FR') }} "
    organization_name: "{{ organization_name | default('Default_Org') }}"
    create_subject_key_identifier: true
  loop: "{{ domains }}"
  run_once: true

- name: Sign certificate for {{ domains }} with TLS CA
  community.crypto.x509_certificate:
    path: "{{ pki_path }}/certs/{{ item }}.crt"
    ownca_path: "{{ pki_path }}/ca/tls-ca/tls-ca.crt"
    ownca_privatekey_path: "{{ pki_path }}/ca/tls-ca/private/tls-ca.key"
    ownca_privatekey_passphrase: "passphrase"
    csr_path: "{{ pki_path }}/ca/{{ item }}.csr"
    provider: ownca
#    key_usage: "{{ key_usage }}"
#    basic_constraints:
#      - "CA:FALSE"
#    extended_key_usage:
#      - serverAuth
  loop: "{{ domains }}"
...
