---
- name: Installation & configuration of chrony
  hosts: serv3
  become: true
  vars:
    chrony_path: /etc/chrony.conf
    pool_ntp_server: debian.pool.ntp.org # use by role
  roles:
    - chrony
