---
- name: Create a full PKI, root-ca, tls-ca, tls-certs
  hosts: serv3
  become: true
  vars:
    role: New_PKI
    ca:
      - root
      - tls
    domains:
      - main.cloud
      - serv1.idrac.cloud
      - serv2.idrac.cloud
      - serv3.idrac.cloud
      - umbrel.local

  tasks:
    - name: Setup folders
      include_role:
        name: "{{ role }}"
        tasks_from: setup_folders

    - name: Setup nginx container
      include_role:
        name: "{{ role }}"
        tasks_from: setup_nginx_docker

    - name: "Setup the {{ ca }}-ca"
      include_role:
        name: "{{ role}}"
        tasks_from: "setup_{{ ca }}_ca"
      loop: "{{ tls }}"

    - name: Deploy the certs
      include_role:
        name: "{{ role }}"
        tasks_from: "generate_certs"
...
