---
- name: Adding an VIP ip
  become: true
  vars:
    physical_interface: none # Put the physical interface by running $ ip link show
    ip_adress: 192.168.1.45

  roles:
    - systemd

  tasks:
       
    - name: Create the config file, add the vip then restart the module
      import_role:
        name: vip
        tasks_from: create_config
...
